### ISSUE TITLE
Greetings of Peace from Singapore

### ISSUE THREAD

**Issue by leexa90** [k7sung/clap2choir#1]
Greetings of Peace brother/sister in Christ,

Could you give a simple explanation of how it works, or perhapes is there anyway i can contact you I would like to adapt the code for audio files. 

Bro Lee XA, TK choir (Singapore)

**Comment by k7sung** [comment]
The script takes the videos from the inputs folder in the Google shared folder and combines them into a single video in a tiled format. It syncs the videos by aligning them at the 4 claps at the beginning of the video. When recording their own videos, every choir members should listen (in an earphone) to the same master track. The master track has 8 metronome ticks at the beginning before music starts. The choir member claps along on the last 4 ticks.

The notebook has some commented out code for audio files. You might be able to just uncomment those lines. The reason those lines were commented out was because I didn't find a way to mix the final combined audio track into the final combined video track.
